name: PyTest and Coverage
run-name: pytest and CodeClimate cov
on: [push]
env:
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: python3 -m pip install .
      - run: python3 -m pip install coverage && python3 -m pip install pytest
      - run: coverage run -m pytest
      - run: coverage xml
      - run: wget https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 && chmod +x test-reporter-latest-linux-amd64
      - run: ./test-reporter-latest-linux-amd64 before-build
      - run: ./test-reporter-latest-linux-amd64 format-coverage coverage.xml  --input-type "coverage.py"
      - run: ./test-reporter-latest-linux-amd64 after-build
      - run: echo "🍏 This job's status is ${{ job.status }}."
